theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: none
theme_advanced_buttons1:
  - bold
  - italic
  - underline
  - removeformat
  - blockquote
  - numlist
  - bullist
  - alignleft
  - aligncenter
  - alignright
  - alignjustify
theme_advanced_buttons2:
theme_advanced_buttons3: